### ISSUE TITLE
Can I contribute the features from my fork? (TypeScript, Browser support, uses "exports")

### ISSUE THREAD

**Issue by alshdavid** [jshttp/mime-types#106]
Hey team, I forked this project and added a few features. Wondering how you felt about the features and if I should spend some time preparing a few PRs to merge them.

- Ported to TypeScript
- Supporting browsers (`path` is extracted)
  - Can use via bundler
  - Can use directly via ESM (imports include `.js` extensions)
- Using the Node16 `exports` property for differential loading in Node

How do you feel about these changes, happy to raise several smaller PRs to incorporate each but don't want to drop a big PR with all these changes in one go and I know things (like TypeScript) are not to taste for some developers.

For reference: https://github.com/alshdavid/mime-types/tree/main

**Comment by dougwilson** [comment]
Hello, and thank you for your generous offer, but I think those changes do not align with the goals of this project, which is to be written in javascript (not typescript) and target as many Node.js versions as possible.

Web browser support is done already by our sister project: `mime`, so I don't think that is necessary here, either.

**Comment by alshdavid** [comment]
That's okay, thanks for letting me know. Thought I'd ask before digging any further. Appreciate the consideration!
