### ISSUE TITLE
Way to override `mime-db`

### ISSUE THREAD

**Issue by chriskuech** [jshttp/mime-types#109]
You mention clearly that requests for new mime types should be made to `mime-db`. This is a longterm solution for not supporting a mime-type, but what should we do in the shortterm? How can we hook into `mime-types` to shim in support for a mime type?

**Comment by dougwilson** [comment]
Override in what way? Just a type or two or the entire thing?

**Comment by chriskuech** [comment]
@dougwilson sorry for the premature submission--just updated the initial post

**Comment by dougwilson** [comment]
Ah, gotcha. So you just add your custom stuff in to https://github.com/jshttp/mime-types#var-type--mimetypesextension and https://github.com/jshttp/mime-types#extensions--mimeextensionstype

**Comment by chriskuech** [comment]
Awesome thanks. Easy enough--

```ts
import { types } from 'mime-types';

types['stp'] = 'model/step';
```
