### ISSUE TITLE
extensions for types with unknown suffixes?

### ISSUE THREAD

**Issue by jonathanong** [jshttp/mime-types#13]
if a suffix is unknown, should we lookup the extension without the suffix?

https://github.com/dherman/module-tag/blob/master/explainer.md#how-do-we-get-there-from-here

**Comment by dougwilson** [comment]
So, to me, this still just seems backwards; I looked around and I cannot find anyone else "abusing" MIME types like this (at least openly). I'm not sure where they pulled `application/javascript+module` from, but I assume the browser isn't treating this custom type any differently from a more proper type: `application/x-javascript-module`.
