### ISSUE TITLE
Detect mimetypes based on file contents instead of path

### ISSUE THREAD

**Issue by NucleaPeon** [jshttp/mime-types#17]
I have the binary contents of a jpg image stored in a cache.

    cache.set('logo', fs.readFileSync("./static/mylogo.jpg"));

Instead of having a separate cache for mimetypes or storing both mimetype and contents in the cache, would it be possible to determine mimetype from the cached data without knowing the path?

Example:

    mime.readMime(cache.get('logo')); # Returns "image/jpg"

**Comment by dougwilson** [comment]
You can do this, yes, but it's definitely beyond the scope of this module, which is just a database (part of the MIME database is what file extensions have been registered for which MIME types, which is how the file path stuff works). You can find modules on `npm` that do this kind of lookup you are seeking through: https://www.npmjs.com/package/mmmagic is an example.

**Comment by NucleaPeon** [comment]
Thank you, that answers my question perfectly.
