### ISSUE TITLE
How should I get the file true type of it?

### ISSUE THREAD

**Issue by tomoat** [jshttp/mime-types#22]
That mimetype is sent by the user, I shouldn't trust it. but I use jshttp/mime-types to  not find the actual mimetype.

How should I get the true type of it?
I will change  “1439542085133.txt”  to "1439542085133.png"

console.log(mime.lookup('/uploads/images/1439542085133.png'));

result  :
image/png

**Comment by dougwilson** [comment]
Hi! This library is simply providing a map of MIME <-> file extension. It sounds like you are looking for something that will actually read the contents of a given file, analyze them, and guess at what the true type is. The library https://github.com/mscdex/mmmagic provides this functionality :)

**Comment by tomoat** [comment]
thank you @dougwilson
