### ISSUE TITLE
audio/mp3 mimetype returns false on extension

### ISSUE THREAD

**Issue by automagisch** [jshttp/mime-types#25]
Looks like mp3 only gets validated on audio/mpeg. So if audio/mp3 is returned (don't say that can't be happening - multer does this.), you only get 'false'.

**Comment by malcolmrebughini** [comment]
This bug should be fixed with this PR https://github.com/jshttp/mime-db/pull/50

**Comment by dougwilson** [comment]
Yea, `audio/mp3` does not return because it's not a real type. @malcolmrebughini identified this as a long-standing Chrome bug and we'll be adding support for it thanks to @malcolmrebughini
