### ISSUE TITLE
Mime type for .tar.gz, .tgz and multipart 7z

### ISSUE THREAD

**Issue by alolis** [jshttp/mime-types#31]
Hello

I wasn't sure if this is the right place to post this or in the `mime-db` project but ... here it goes...

At the moment, `lookup` will not work if a file ends in `.tar.gz` or `.tgz` or if it's a multipart `7z` archives which they end in `.7z.001`, `7z.002` etc.

Is this something that `mime-types` has to support or `mime-db`? Any solutions would appreciated 

Cheers!

**Comment by dougwilson** [comment]
Hi @alolis yes, this project is just an access point to the data in the `mime-db` project, and doesn't have any mappings directly in the source code here to modify. You'll need to get those mappings added to the projects that `mime-db` aggregates from, namely Apache or NGINX.

I hope this helps!
