### ISSUE TITLE
mime lookup for application/json returns false

### ISSUE THREAD

**Issue by pcgilday** [jshttp/mime-types#32]
Passing "application/json" to the `mime.lookup` returns false. I am assuming this is a bug and that passing a valid mime-type to `mime.lookup` should return that same mime-type. Also, the README says this behaves similarly to [the mime module](https://www.npmjs.com/package/mime) which handles this type the way I would expect. Examples below. 

Using `mime-types`

```js
12:33 $ node
> const mime = require('mime-types')
> mime.lookup('application/json')
false
> mime.lookup('json')
'application/json'
>
```

Using `mime`

```js
12:38 $ node
> const mime = require('mime')
> mime.lookup('application/json')
'application/json'
> mime.lookup('json')
'application/json'
>
```

If this is the intended behavior, then it should probably be mentioned as a difference between this and the `mime` package (along with the other differences called out) in the README.

Happy to help out with a PR if this is indeed a bug and not the intended behavior

**Comment by dougwilson** [comment]
You're encountering a bug in `mime` itself. You see, you're passing in `application/json` and that module incorrectly thing you're looking for the file `json` and then incorrectly things the file extension for that is `json`. You can see it's _not_ echoing the type if you do
```
 node
> const mime = require('mime')
> mime.lookup('text/plain')
'application/octet-stream'
>
```

**Comment by dougwilson** [comment]
This is the bug: https://github.com/broofa/node-mime/issues/113

**Comment by dougwilson** [comment]
And this module fixed the bug (which is one of the purposes of this module: incorporate bug fixes that `mime` is not fixing :) ).

**Comment by dougwilson** [comment]
I updated the blurb in the README to note that there are bug fixes to the `.lookup` method compared to the `mime` module.

**Comment by pcgilday** [comment]
Thank you for clarifying, I misunderstood the use case for the lookup function initially.
