### ISSUE TITLE
no support for heic / heif image formats 

### ISSUE THREAD

**Issue by adylevy** [jshttp/mime-types#40]
iOS 11 brought full support for HEIC formats. this is becoming very popular and not having it in the list will cause issues to mime-types users.

http://nokiatech.github.io/heif/technical.html

**Comment by dougwilson** [comment]
There isn't a change this module can makr to support this. You already opened a duplicate issue in the correct module, though.

**Comment by farhanmannan** [comment]
Which module is that @dougwilson  ?
