### ISSUE TITLE
New Version ETA

### ISSUE THREAD

**Issue by mike1808** [jshttp/mime-types#44]
Hi, can you say when do you plan to publish a new version with updated mime-db? I need mime type for WebAssembly files [zeit/serve#303](https://github.com/zeit/serve/issues/303)

**Comment by dougwilson** [comment]
Hi! I have been working on it and sorry the wasm addition happened in the same release as all the font changes. The font changes look like they are causing some issues which I've been trying to work through with a couple projects before pulling them in here and increasing thr fallout.

**Comment by leo** [comment]
👋 Would be great if you could release this soon. Thanks ❤️

**Comment by giuseppeg** [comment]
bumping since I'd need this change too :)

**Comment by giuseppeg** [comment]
@dougwilson can you release a patch version?

**Comment by dougwilson** [comment]
@giuseppeg please see https://github.com/jshttp/mime-types/issues/44#issuecomment-352190061 . I haven't gotten the change to address the font issues, which is blocking this release.

**Comment by dougwilson** [comment]
You can add any mapping to this module in addition to the built-in mappings. For example: `mime.types['wasm'] = 'application/wasm'`

**Comment by philipp-spiess** [comment]
Would it make sense to temporarily add `mime.types['wasm'] = 'application/wasm'` directly to this package to avoid upgrading `mime-db`?

I guess all we have to do is initialize [this object here](https://github.com/jshttp/mime-types/blob/master/index.js#L37), right? I can provide a PR if you want to 👍

**Comment by dougwilson** [comment]
No, @philipp-spiess that would be rejected. This module is *only* designed to be a wrapper to `mime-db`; it's an extremely slippery slope to start just adding more and more types manually here.

**Comment by giuseppeg** [comment]
@dougwilson gotcha. I definitely don't want to put pressure on you. I am just wondering whether it'd possible to do two separate releases and get the wasm fix now. After all versions are free :) 

Production apps (packages that depend on this package) are affected by the issue (including @zeithq's deployments). ) I don't have context though so I'd just shut up and wait for the fix in case this is not possible.

**Comment by dougwilson** [comment]
I'm not sure what the separate releases would be. Releasing a new version will break existing servers, but I guess you get wasm support. Why is that acceptable? WASM was never served for a long time with any type, so nothing has been broken here. You just want to take advantage of something new, and new types come out all the time. Just add the entry to your server code if you want to serve WASM files for the time being. It's just one line.

**Comment by giuseppeg** [comment]
fair enough, thanks for your patience.

**Comment by dougwilson** [comment]
Published version 2.1.18 👍
