### ISSUE TITLE
xml mime type handling

### ISSUE THREAD

**Issue by tudor33sud** [jshttp/mime-types#48]
Xml type is by the standard allowed to use 2 separate mime types: application/xml and text/xml .

"If an XML document -- that is, the unprocessed, source XML document -- is readable by casual users, text/xml is preferable to application/xml. MIME user agents (and web user agents) that do not have explicit support for text/xml will treat it as text/plain, for example, by displaying the XML MIME entity as plain text. Application/xml is preferable when the XML MIME entity is unreadable by casual users."

I'm facing an issue where I upload data from the web client, mime type is interpreted as text/xml, but on the backend library defaults to application/xml. Is there already a way of configuring this under the library? Or is there any good approach for this?

Thank you

**Comment by dougwilson** [comment]
You can edit the maps in https://github.com/jshttp/mime-types#var-type--mimetypesextension to change the results of the look ups, if that's what you're looking for.

**Comment by tudor33sud** [comment]
Oh, my bad! That would do then! Although, unfortunately, I don t think there s an easy way for this kind of cases to use 2 mimetypes for the same extension. I saw there s an issue related to a lookupall method, which may come in handy. 

Thank you
