### ISSUE TITLE
When I debug in Webstorm, the populateMaps function in index.js takes nearly over 1 minute

### ISSUE THREAD

**Issue by samjross** [jshttp/mime-types#49]
My project has the following dependencies

```
   "config": "^1.30.0",
    "fs-extra": "^5.0.0",
    "js-yaml": "^3.11.0",
    "node-mailjet": "^3.2.1",
    "request": "^2.85.0",
    "request-promise": "^4.2.2"
```

I believe 'request' is the one that requires mime-types.

I'm running windows 10, node 8.9.1, most recent version of Webstorm

```
WebStorm 2017.3.5
Build #WS-173.4674.32, built on March 5, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

When I debug a project in webstorm, it runs it like this: `"C:\Program Files\nodejs\node.exe" --inspect-brk=50305 D:\Projects\Project\test.js`

When debugging, my app always took a minute to start up, much longer than when not debugging, so I traced it down to mime-types index.js, traced it down to the `Object.keys(db).forEach` loop, and timed each loop, both when debugging and when not debugging

When not debugging, every `type` in the forEach loop takes under 2 ms. When debugging, most of the types take between 30 and 60 ms, some over 100ms.

**Comment by dougwilson** [comment]
Very strange. Open to hearing a solution! Not sure if this is a bug in the debugger itself or just something modules need to address in some way. Let me know :+1:

**Comment by dougwilson** [comment]
Maybe it's a bug in the debugger?

**Comment by dougwilson** [comment]
Closing due to unknown action this module can possibly take.
