### ISSUE TITLE
v2.1.19 is breaking builds with "Cannot find module 'mime-types'" error

### ISSUE THREAD

**Issue by 4cm4k1** [jshttp/mime-types#55]
Hi,

The latest release of `mime-types` (https://github.com/jshttp/mime-types/tree/2.1.19) seems not to expose the module, causing the following error output when trying to build:

```shell
> [0] website@0.0.1 start /home/nowuser/src
> [0] node index.js
> [0]
> [0] internal/modules/cjs/loader.js:550
> [0]     throw err;
> [0]     ^
> [0]
> [0] Error: Cannot find module 'mime-types'
> [0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
> [0]     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
> [0]     at Module.require (internal/modules/cjs/loader.js:598:17)
> [0]     at require (internal/modules/cjs/helpers.js:11:18)
> [0]     at Object.<anonymous> (/home/nowuser/src/node_modules/superstatic/lib/responder.js:11:12)
> [0]     at Module._compile (internal/modules/cjs/loader.js:654:30)
> [0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
> [0]     at Module.load (internal/modules/cjs/loader.js:566:32)
> [0]     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
> [0]     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
> [0] npm ERR! code ELIFECYCLE
> [0] npm ERR! errno 1
> [0] npm ERR! website@0.0.1 start: `node index.js`
> [0] npm ERR! Exit status 1
> [0] npm ERR!
> [0] npm ERR! Failed at the website@0.0.1 start script.
> [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [0]
> [0] npm ERR! A complete log of this run can be found in:
> [0] npm ERR!     /home/nowuser/.npm/_logs/2018-07-18T21_33_33_441Z-debug.log
> [0] The process exit before binding to a port. Maybe 'listen()' is missing?
> [0] More details: https://err.sh/now-cli/no-open-port-found
> Error! Instance verification timed out (3m)
> Read more: https://err.sh/now-cli/verification-timeout
```

**Comment by dougwilson** [comment]
Weird. I don't think I did anything different from previous versions. Do you know what the fix I need to do is? Or if not, can you provide complete steps I can perform to reproduce the issue so I can investigate?

**Comment by 4cm4k1** [comment]
I'm looking more closely into it, but as a workaround, I added `mime-types` to my dependencies and specified version `2.1.18`, which works without issue. I'll update if I narrow down the issue. (I'm using `superstatic`, which depends on it.)

**Comment by dougwilson** [comment]
Ok. This is what I tried to test the assertion "seems not to expose the module":

```
$ mkdir mime-types-55

$ cd mime-types-55/

$ npm i mime-types@2.1.19
mime-types-55
`-- mime-types@2.1.19
  `-- mime-db@1.35.0

$ node -pe 'require("mime-types").lookup(".json")'
application/json
```

Can you try these same steps? Or do you know if these steps represent the issue you're describing? If not, where is my misunderstanding?

Would like to fix ASAP, please, because this is a major module. At least provide steps to reproduce the issue to posted so I can investigate in parallel.

**Comment by 4cm4k1** [comment]
I tried those steps without issue; I'm trying to make a repo demonstrating the repro now.

**Comment by dougwilson** [comment]
So I have to leave for an emergency so I cannot take any further look likely until tomorrow. Please post when you can and I'll get to this as soon as I can.

**Comment by 4cm4k1** [comment]
That's okay. I'm unable to reproduce this locally, so it may not actually be an issue with this package, but rather have something to do with my cloud provider Zeit Now (https://github.com/zeit/now-cli). A number of other individuals reported the issue in Zeit's community Slack, but we're all getting by with specifying `2.1.18` as a dependency version. Their staff are looking into it on their end, too.

**Comment by dougwilson** [comment]
Thanks for the update :+1: I'm still on phone for now, so read your message. It sounds like there isn't an action item this module can take at this time. If you have something we need to change or something I can look at, I'll be happy to reopen the issue :+1:

**Comment by 4cm4k1** [comment]
Yep. Zeit's fixed it on their end. The cache for this package was corrupted, so they purged the cache. Thanks for your quick replies, and sorry for the false alarm. 😄
