### ISSUE TITLE
Inconsistencies  with require.js and mime-db

### ISSUE THREAD

**Issue by ovidiucirstea** [jshttp/mime-types#61]
Hello, 

I have found some issues when I tried to add mime-types to my project.
Please take a look at my 2 comments.

missing mime-db: 
"mime-db": "~1.39.0" => ERROR: bower ENOTFOUND     Package mime-db not found
"mime-db": "git://github.com/jshttp/mime-db.git", => this way I can add the mime-db independent from mime-types
 
missing require
"requirejs": "~2.3.6", => is also needed in my project (would be nice to have it in the dependencies)

Thank you

**Comment by dougwilson** [comment]
I'm not sure what those errors mean or how to help resolve them.
