### ISSUE TITLE
Some popular programming language extensions are not recognized

### ISSUE THREAD

**Issue by zadam** [jshttp/mime-types#62]
Hello, I did some testing and it seems like a bunch of popular programming languages are not recognized based on extension. I used `mimeTypes.lookup(ext)` for testing which in cases below returned `false`. I added MIME type I understand should be correct for these extensions:

```
.cs => text/x-csharp
.clj => text/x-clojure
Dockerfile => text/x-dockerfile
.erl, .hrl => text/x-erlang
.feature => text/x-feature
.go => text/x-go
.groovy => text/x-groovy
.hs, .lhs => text/x-haskell
.http => message/http
.kt => text/x-kotlin
.m => text/x-objectivec
.py => text/x-python
.rb => text/x-ruby
.scala => text/x-scala
.swift => text/x-swift
```

**Comment by dougwilson** [comment]
https://github.com/jshttp/mime-types#adding-types
