### ISSUE TITLE
cannot identify some fonts extensions form mime-type

### ISSUE THREAD

**Issue by alonronin** [jshttp/mime-types#63]
the following mime-types are returning `false` instead of the expected extension:

- application/x-font-ttf - expected `ttf`
- application/font-woff - expected `woff`
- application/font-woff2 - expected `woff2`

BTW, is there a way to add additional mime-tyeps extensions at runtime?

**Comment by dougwilson** [comment]
For the first part of your issue, it should be answered by this part of the readme: https://github.com/jshttp/mime-types#adding-types

For the second part, there is an open PR already tracking that feature request: https://github.com/jshttp/mime-types/pull/34

**Comment by Rotzbua** [comment]
@alonronin `application/font-woff2` is deprecated. Since 2017 it is recommended to use `font/woff2` defined in RFC8081.
