### ISSUE TITLE
Unexpected end of JSON input while parsing near '...8b15bac4a1aefb9af05b0'

### ISSUE THREAD

**Issue by linxd-cheer** [jshttp/mime-types#64]
hi,  I get a error , how to fix it? 
![image](https://user-images.githubusercontent.com/50398651/61448160-f607e300-a984-11e9-9cd4-7a38b2ab46e2.png)
```
npm ERR! Unexpected end of JSON input while parsing near '...8b15bac4a1aefb9af05b0'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\linxd\AppData\Roaming\npm-cache\_logs\2019-07-18T09_49_50_420Z-debug.log
```

npm version is 5.6.0

hope get someone reply, thx

**Comment by dougwilson** [comment]
Please provide that error log here.

**Comment by linxd-cheer** [comment]
> Please provide that error log here.

error log: 

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node10.15\\node-v10.2.1\\node.exe',
1 verbose cli   'D:\\node10.15\\node-v10.2.1\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'mime-types' ]
2 info using npm@5.6.0
3 info using node@v10.2.1
4 verbose npm-session 3fa8fe97f9bd7cf6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/mime-types 882ms (from cache)
8 silly fetchPackageMetaData error for mime-types@latest Unexpected end of JSON input while parsing near '...8b15bac4a1aefb9af05b0'
9 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...8b15bac4a1aefb9af05b0'
9 verbose stack     at JSON.parse (<anonymous>)
9 verbose stack     at parseJson (D:\node10.15\node-v10.2.1\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
9 verbose stack     at consumeBody.call.then.buffer (D:\node10.15\node-v10.2.1\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
10 verbose cwd D:\workspace
11 verbose Windows_NT 10.0.17763
12 verbose argv "D:\\node10.15\\node-v10.2.1\\node.exe" "D:\\node10.15\\node-v10.2.1\\node_modules\\npm\\bin\\npm-cli.js" "install" "mime-types"
13 verbose node v10.2.1
14 verbose npm  v5.6.0
15 error Unexpected end of JSON input while parsing near '...8b15bac4a1aefb9af05b0'
16 verbose exit [ 1, true ]

**Comment by dougwilson** [comment]
Thanks. It looks like your local npm cache is probably corrupted. Can you run `npm cache clean --force` and then try installing again?

**Comment by linxd-cheer** [comment]
> Thanks. It looks like your local npm cache is probably corrupted. Can you run `npm cache clean --force` and then try installing again?

Thanks your answer, it's work well
