### ISSUE TITLE
Mp3 vs Mpga inconsistency

### ISSUE THREAD

**Issue by SeanCannon** [jshttp/mime-types#65]
Interesting mismatch here, though the files seem to work the same either way. We're using AWS MediaConvert, setting mime-type with this library before processing, and then we're setting the file extension with this library before sending back to the browser. When someone uploads a `.mp3` file, they end up getting back a `.mpga` file. Several variants of the file are created and it's not an option right now to preserve the extension as a string before we process it. 

Simple reproduce : 
```
> const mime = require('mime-types');
> mime.lookup('foo.mp3');
'audio/mpeg'
> mime.extension('audio/mpeg');
'mpga'
```

**Comment by georgezhang** [comment]
@SeanCannon May I know how did you solve this problem?

**Comment by endoooo** [comment]
@georgezhang I stumbled upon this issue and I solved it by simply not using the `mime.extension(MIMEType)` function when I have access to the file name. something like this:

```javascript
/**
 * Returns the file extension
 *
 * @param {(Object|string)} file - File, Blob or filename/path
 * @returns {string} the file extension
 */
function getFileExtension(file) {
  // we will prioritize file name extraction to prevent mismatchs
  if (typeof file === 'string' || file instanceof File) {
    // use file name prop or file itself (that should be a string)
    const filename = file?.name || file
    const extMatch = filename.match(/(?<=\.)\w+$/)
    return extMatch ? extMatch[0] : ''
  }

  // if blob, use MIME type to get default extension
  const fileMIMEType = file?.type
  if (fileMIMEType === 'audio/amr') return 'amr' // temp solution for lib missing support
  if (fileMIMEType === 'audio/amr-wb') return 'awb' // temp solution for lib missing support
  return mime.extension(fileMIMEType) || ''
}
```

**Comment by wahidshafique** [comment]
@SeanCannon Did you manage to fix this/find a work around?

**Comment by SeanCannon** [comment]
Product sort of solved this one for us by forcing us to use a mime-type whitelist, only allowing uploads of certain types in each prompt, so we had to manually infer the mime from the extension and then let opswat handle any sneaky people renaming their virus.exe to friendly.mp3 or something. Wish I had a more elegant solution for you guys 🤷
