### ISSUE TITLE
`image/svg+xml` charset

### ISSUE THREAD

**Issue by connorjclark** [jshttp/mime-types#66]
Current:
```
mime.charset('image/svg+xml') === false
```

Expected:
```
mime.charset('image/svg+xml') === 'UFT-8'
```

**Comment by dougwilson** [comment]
Thanks for the report. The data for that comes from the `mime-db` project (https://github.com/jshttp/mime-db). If you would like to see this module return that value, I would suggest to just open a pull request at that module to get it added and it will get pulled in here automatically.

https://github.com/jshttp/mime-db#contributing
