### ISSUE TITLE
Module not found: Error: Can't resolve 'path' in app/node_modules/mime-types

### ISSUE THREAD

**Issue by wcjord** [jshttp/mime-types#69]
I added the path dependency back into the mime-types/package.json and that fixed the problem. I see that this path dependency was been a discussion topic in the past. Was the dependency added back in recent versions? I'm using mime-types@2.1.25

```
Ionic:

   Ionic CLI                     : 5.4.13 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.7
   @angular-devkit/build-angular : 0.803.21
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.1.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 7.1.4, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 16 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.3.0

System:

   ios-deploy : 2.0.0
   ios-sim    : 8.0.2
   NodeJS     : v10.18.0 (/usr/local/Cellar/node@10/10.18.0/bin/node)
   npm        : 6.13.4
   OS         : macOS Mojave
   Xcode      : Xcode 11.2.1 Build version 11B500

```

**Comment by dougwilson** [comment]
The `path` package is part of the Node.js runtime: https://nodejs.org/dist/latest-v12.x/docs/api/path.html

Adding it to the package.json installs a different module than the one built into Node.js.

**Comment by dougwilson** [comment]
Please see https://github.com/jshttp/mime-types/issues/50#issuecomment-442916069

**Comment by wcjord** [comment]
Thank you so much!

**Comment by anuj9196** [comment]
It seems `mime` as referenced in #50  is not more maintained. Their [repo](https://github.com/broofa/node-mime) has been marked read only and says

> This module is now maintined at https://github.com/kelektiv/node-uuid
