### ISSUE TITLE
Change file name extention

### ISSUE THREAD

**Issue by kiettanle** [jshttp/mime-types#70]
I have a JSON file _example.json_. 
I changed the file name to _example.png_ then I uploaded that file to the server. 
Then I uploaded the uploaded file to S3 Storage. 
Then I downloaded the file from S3 to the local machine. I couldn't view it as an image.
Then I changed the filename to _example.json_. I could view the content of the file.
This will lead to **Malicious file type could be uploaded and leading to Cross-site scripting attack**

What can I do to stop it?
Thanks!

**Comment by dougwilson** [comment]
Duplicate of #67
