### ISSUE TITLE
Missing MimeType for keynote

### ISSUE THREAD

**Issue by alex-p-mai** [jshttp/mime-types#74]
In the mime-db 1.43.0, there's an entry for .keynote, however when I pass in 'asdadad.keynote', mime-types returns false.

```
"application/vnd.apple.keynote": {
    "source": "iana",
    "extensions": ["keynote"]
  },
```

**Comment by dougwilson** [comment]
What version of `mime-types` are you using?

**Comment by alex-p-mai** [comment]
> What version of `mime-types` are you using?

"mime-types": "^2.1.26",

**Comment by dougwilson** [comment]
I'm not able to reproduce your issue. Here are the steps I took below. If you can provide the specific steps to replicate your issue, that would be of great help!
```
$ mkdir mime-types-74
$ cd mime-types-74/
$ npm i 'mime-types@^2.1.26'
+ mime-types@2.1.26
added 2 packages from 4 contributors and audited 2 packages in 0.815s
found 0 vulnerabilities
$ node -pe 'require("mime-types").lookup("asdadad.keynote")'
application/vnd.apple.keynote
```

**Comment by alex-p-mai** [comment]
> I'm not able to reproduce your issue. Here are the steps I took below. If you can provide the specific steps to replicate your issue, that would be of great help!
> 
> ```
> $ mkdir mime-types-74
> $ cd mime-types-74/
> $ npm i 'mime-types@^2.1.26'
> + mime-types@2.1.26
> added 2 packages from 4 contributors and audited 2 packages in 0.815s
> found 0 vulnerabilities
> $ node -pe 'require("mime-types").lookup("asdadad.keynote")'
> application/vnd.apple.keynote
> ```

Apologies. It looks like Apple changed their file extension to .key instead of .keynote, which is why it's not being picked up correctly. My file name was asdadad.key.
