### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by john050481** [jshttp/mime-types#79]
please tell me, when will be the new package released mime-types?
@dougwilson 
https://github.com/jshttp/mime-db/releases/tag/v1.45.0

**Comment by FourCinnamon0** [comment]
What does the current one lack?

**Comment by chrisweb** [comment]
@FourCinnamon0 https://github.com/jshttp/mime-db/blob/master/HISTORY.md ... so for example AVIF

**Comment by chrisweb** [comment]
ping @dougwilson do you think we can merge this?
