### ISSUE TITLE
Issue for rar file

### ISSUE THREAD

**Issue by ajouve** [jshttp/mime-types#85]
Hi,

rar file seems to be `application/x-rar` and not `application/vnd.rar`

**Comment by dougwilson** [comment]
Hi @ajouve sorry for any confusion. This module gets those mappings from a dependency: https://github.com/jshttp/mime-types#adding-types

**Comment by dougwilson** [comment]
As a follow up it seems that the registration at the IANA is for `application/vnd.rar` https://www.iana.org/assignments/media-types/application/vnd.rar
