### ISSUE TITLE
Map quicktime files to .mov and not .qt extensions

### ISSUE THREAD

**Issue by zstuder25** [jshttp/mime-types#90]
When calling mime.extension("video/quicktime") it should return "mov" instead of "qt" since "qt is now deprecated. Both are available from mime-db but it seems to always select "qt" which leads to some problems.

**Comment by dougwilson** [comment]
Thank you for this information. Can you provide the source that states what you said above?

**Comment by zstuder25** [comment]
I'll try and provide as much context as I can as I'm not sure what you're specifically asking for. The [.qt file extension](https://discussions.apple.com/thread/951061) was deprecated in favor of the .mov extensions but are equivalent and can be seen in the mime-db generated file and talked about in this issue here https://github.com/jshttp/mime-db/issues/86
The reason is the .qt file extension is also not supported by all browsers since it has been deprected. 

To reproduce the issue with mime-type library here, simply import/require the library and call 
```mime.extension("video/quicktime")``` and it will return ```"qt"```, I propose it should return ```"mov"``` instead as default given that it is the currently supported file extension.

**Comment by dougwilson** [comment]
I was mainly looking for documentation from Apple or something that stated this. If you say the web browsers don't support it, maybe documentation to that extent. But in the meantime, I tracked it down and this data is coming from the Apache project. Ideally you can get them to fix it and it will show up here.

If you think that we should special case this one extension, then I will need some more official documentaion that it is deprecated, ideally from the owner Apple, and not just a random forum link.

Ultimately, though, this is a change that woupd need to be made upstream of the project, either in `mime-db` if presented official documentation from Apple that the extension for thier mime type is deprecated or in the Apache project with however they would like to handle it.
