### ISSUE TITLE
Option for `.jpg`

### ISSUE THREAD

**Issue by J-P-S-O** [jshttp/mime-types#94]
```javascript
let mime = require("mime-types")
mime.extension("image/jpeg")
```
will return "jpeg". Due to specific reasons, I have some images that need to be saved in ~~.jpg~~ the original format, `.jpg`. It would be handy if there was an option to force certain mime-types to correspond to some extensions. Like:
```javascript
let mime = require("mime-types")
mime.force("image/jpeg", "jpg")
mime.extension("image/jpeg") // now returns jpg
```

**Comment by dougwilson** [comment]
Hi @J-P-S-O just change the mapping for that type to extension:
```js
require('mime-types').extensions["image/jpeg"] = "jpg"
```

**Comment by J-P-S-O** [comment]
@dougwilson Thanks!
