### ISSUE TITLE
`contentType` does not work for paths

### ISSUE THREAD

**Issue by jeffmcaffer** [jshttp/mime-types#97]
The doc shows an example of using `contentType` on a path. Unfortunately, it doesn't seem to work. 

```javascript
mime.contentType(path.extname('/path/to/file.json')) // 'application/json; charset=utf-8'
```

Looking at [the code](https://github.com/jshttp/mime-types/blob/master/index.js#L83) (below) it seems that anything that has a `/` is assumed to be a mime type. 

```javascript
  var mime = str.indexOf('/') === -1
    ? exports.lookup(str)
    : str
```
As a result you just get your path back from the `contentType` call.

**Comment by dougwilson** [comment]
Hello, sorry about that! Can you elaborate more on how the example doesn't work? The example shows how to use it with a path by using the `path.extname` function, not that you can pass in the path directly as the argument to `.contentType`.

**Comment by jeffmcaffer** [comment]
sigh. totally my bad. actually didn't notice the `path.extname` and was expecting to call `contentType` like one calls `lookup` (that is, you can pass in the whole path like `mime.lookup('folder/file.js') // 'application/javascript'`.
