### ISSUE TITLE
Not correctly typing d.ts typingsfiles of Typescript. Returns video/mp2t.

### ISSUE THREAD

**Issue by Sagato** [jshttp/mime-types#99]
### Current Behavior

When trying to guess the mime type of a typescript typingsfile the package returns 'video/mp2t'.

### Wanted Behavior

return the correct mime type.

**Comment by dougwilson** [comment]
Hello, sorry you are having an issue. All types come from the dependency `mime-db` and would need to be changed there, as this module is just an API over that module and doesn't contain any mappings itself.
